apiVersion: v1
kind: Service
metadata:
  {{- $metadata := dict "name" .Values.server.name "Chart" .Chart "Release" .Release }}
  {{- include "rustdok.commonMetadata" $metadata | nindent 2 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.server.name }}
    release: {{ .Release.Name }} 