{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $metadata := dict "name" .Values.webui.name "Chart" .Chart "Release" .Release }}
  {{- include "rustdok.commonMetadata" $metadata | nindent 2 }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webui.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webui.name }}
        release: {{ .Release.Name }}
      {{- with .Values.webui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.webui.name }}
          image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webui.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.webui.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.webui.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.webui.livenessProbe.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.webui.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.webui.livenessProbe.failureThreshold | default 3 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.webui.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.webui.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.webui.readinessProbe.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.webui.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.webui.readinessProbe.failureThreshold | default 3 }}
          env:
            {{- include "rustdok.webuiEnvVars" . | nindent 12 }}
            {{- if .Values.webui.env.extraEnvs }}
            {{- toYaml .Values.webui.env.extraEnvs | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
{{- end }} 