{{- if .Values.server.gatewayapi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
   {{- $metadata := dict "name" .Values.server.name "Chart" .Chart "Release" .Release }}
   {{- include "rustdok.commonMetadata" $metadata | nindent 2 }}
spec:
  parentRefs:
    {{- range .Values.server.gatewayapi.parentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
    {{- end }}
  hostnames:
    {{- range .Values.server.gatewayapi.hostnames }}
    - {{ . }}
    {{- end }}
  rules:
    - backendRefs:
        - kind: Service
          name: {{ .Values.server.name }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.server.service.port }}
{{- end }}
---
{{- if .Values.webui.gatewayapi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- $metadata := dict "name" .Values.webui.name "Chart" .Chart "Release" .Release }}
  {{- include "rustdok.commonMetadata" $metadata | nindent 2 }}
spec:
  parentRefs:
    {{- range .Values.webui.gatewayapi.parentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
    {{- end }}
  hostnames:
    {{- range .Values.webui.gatewayapi.hostnames }}
    - {{ . }}
    {{- end }}
  rules:
    - backendRefs:
        - kind: Service
          name: {{ .Values.webui.name }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.webui.service.port }}
{{- end }}