name: Release Charts

on:
  push:
    branches:
      - main

env:
  ORG_NAME: devs-in-the-cloud
  
jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.DITC_CR }}"
        with:
          charts_dir: charts
          config: cr.yaml

      # Add OCI registry support
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DITC_CR }}
          
      - name: Get Chart Version
        id: chart_version
        run: |
          VERSION=$(grep 'version:' charts/rustdok/Chart.yaml | awk '{print $2}' | tr -d '\r')
          echo "chart_version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Package and Push Chart to OCI Registry
        run: |
          # Package the chart
          helm package charts/rustdok
          
          # Push to OCI registry
          helm push rustdok-${{ steps.chart_version.outputs.chart_version }}.tgz oci://ghcr.io/$ORG_NAME/charts
          
          echo "Chart pushed to OCI registry: oci://ghcr.io/$ORG_NAME/charts/rustdok:${{ steps.chart_version.outputs.chart_version }}" 